'''
Created on 21 Oct 2014
@author: Nickel
'''

from npcs.npc import *

npcList = []

#Note: drawing quads seems to be incredibly slow. Recommend not using more than 5 NPC's per map until fixed
def createNPCList(scene): #add NPC's here. Additional features will be added later.
    global npcList
    if scene == "town1":
        npc1 = npc("town1", 21, 11, "down", "sprites/ghost1SpriteSheet1.png")
        npc1.setText("Geez, like, get out of my way!")
        npc1.setText("Can't you see I'm brooding over here?")
        npc1.setText("Just leave me alone!")
        npcList.append(npc1)
        npc1 = npc("town1", 7, 7, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("town1", 13, 8, "right", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("town1", 14, 6, "up", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("town1", 10, 9, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("town1", 11, 9, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("town1", 12, 9, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("town1", 13, 9, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("town1", 14, 9, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("town1", 15, 9, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("town1", 16, 9, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("town1", 17, 9, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("town1", 18, 9, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("town1", 19, 9, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("town1", 20, 9, "left", "sprites/ghost1SpriteSheet1.png")
        npc1.setText("Hi! I'm different!")
        npc1.setText("Can't you tell?")
        npc1.setText("I know me and my 14 brothers are similar, but...")
        npcList.append(npc1)
    if scene == "map1":
        
        npc1 = npc("town1", 21, 11, "down", "sprites/ghost1SpriteSheet1.png")
        npc1.setText("Use WASD to move around")
        npc1.setText("enter to interact with things")
        npc1.setText("and escape to pause")
        npcList.append(npc1)
        npc1 = npc("town1", 7, 7, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("town1", 13, 20, "right", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("town1", 14, 6, "up", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("town1", 15, 9, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("town1", 28, 10, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("town1", 12, 12, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("town1", 22, 17, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("town1", 14, 23, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("town1", 15, 9, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("town1", 18, 23, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("town1", 17, 1, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("town1", 20, 19, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("town1", 19, 10, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("town1", 20, 9, "left", "sprites/ghost1SpriteSheet1.png")
        npc1.setText("Hi! I'm different!")
        npc1.setText("Can't you tell?")
        npc1.setText("I know me and my 14 brothers are similar, but...")
        npcList.append(npc1)
        
    if scene == "pseudocampusmap":
        
        npc1 = npc("pseudocampusmap", 21, 11, "down", "sprites/ghost1SpriteSheet1.png")
        npc1.setText("Geez, like, get out of my way!")
        npc1.setText("Can't you see I'm brooding over here?")
        npc1.setText("Just leave me alone!")
        npcList.append(npc1)
        npc1 = npc("pseudocampusmap", 12, 7, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("pseudocampusmap", 9, 20, "right", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("pseudocampusmap", 17, 6, "up", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("pseudocampusmap", 17, 9, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("pseudocampusmap", 28, 10, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("pseudocampusmap", 12, 12, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("pseudocampusmap", 23, 17, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("pseudocampusmap", 15, 23, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("pseudocampusmap", 15, 9, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("pseudocampusmap", 18, 23, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("pseudocampusmap", 17, 2, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("pseudocampusmap", 20, 19, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("pseudocampusmap", 19, 10, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("pseudocampusmap", 20, 9, "left", "sprites/ghost1SpriteSheet1.png")
        npc1.setText("Hi! I'm different!")
        npc1.setText("Can't you tell?")
        npc1.setText("I know me and my 14 brothers are similar, but...")
        npcList.append(npc1)
    if scene == "fortesmap":        
        npc1 = npc("fortesmap", 21, 11, "down", "sprites/ghost1SpriteSheet1.png")
        npc1.setText("Use WASD to move around")
        npc1.setText("enter to interact with things")
        npc1.setText("and escape to pause")
        npcList.append(npc1)
        npc1 = npc("fortesmap", 12, 7, "left", "sprites/ghost1SpriteSheet1.png")
        npc1.setText("Use WASD to move around")
        npc1.setText("enter to interact with things")
        npc1.setText("and escape to pause")
        npcList.append(npc1)
        npc1 = npc("fortesmap", 9, 20, "right", "sprites/ghost1SpriteSheet1.png")
        npc1.setText("Use WASD to move around")
        npc1.setText("enter to interact with things")
        npc1.setText("and escape to pause")
        npcList.append(npc1)
        npc1 = npc("fortesmap", 17, 6, "up", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("fortesmap", 17, 9, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("fortesmap", 29, 8, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("fortesmap", 12, 12, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("fortesmap", 23, 19, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("fortesmap", 15, 23, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("fortesmap", 15, 9, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("fortesmap", 18, 23, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("fortesmap", 17, 2, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("fortesmap", 20, 19, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("fortesmap", 19, 10, "left", "sprites/ghost1SpriteSheet1.png")
        npcList.append(npc1)
        npc1 = npc("fortesmap", 15, 9, "left", "sprites/ghost1SpriteSheet1.png")
        npc1.setText("Hi! I'm different!")
        npc1.setText("Can't you tell?")
        npc1.setText("I know me and my 14 brothers are similar, but...")
        npcList.append(npc1)

def getNPCList():
    global npcList
    return npcList